pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        getRubyVersion()
        installPackages()
      }
    }
  }
}

def getRubyVersion() {
  sh 'ruby -v'
}

def installPackages() {
  sh 'gem install bundler'
  sh 'bundle install --jobs 6'
}
