pipeline {
  agent any
  stages {
    stage('Setup') {
      steps {
        getRubyVersion()
        installPackages()
        createDatabase()
      }
    }
    stage('Security Checks, Code Analysis and Test') {
      parallel {
        stage('Security Checks') {
          runSecurityChecks()
        }
        stage('Code Analysis') {
          runCodeAnalysis()
        }
        stage('Test') {
          runTest()
        }
      }
    }
  }
}

def getRubyVersion() {
  sh 'ruby -v'
}

def installPackages() {
  sh 'gem install bundler'
  sh 'bundle install --jobs 6'
}

def createDatabase() {
  sh 'bundle exec rake db:setup'
}

def runSecurityChecks() {
  sh 'bundle-audit update'
  sh 'bundle-audit check'
}

def runCodeAnalysis() {
  sh 'rubocop'
}

def runTest() {
  sh 'rspec'
}
