default: &default
  services:
    quote_application:
      secret_key: <%= ENV['WEBSERVICE_QUOTE_APP_SECRET'] %>
      expires_at: <%= ENV['WEBSERVICE_QUOTE_APP_EXPIRES_AT'] %>
      encryption_type: <%= ENV['WEBSERVICE_ENCRYPTION_TYPE'] %>
    agreements_application:
      secret_key: <%= ENV['WEBSERVICE_AGREEMENTS_APP_SECRET'] %>
      expires_at: <%= ENV['WEBSERVICE_AGREEMENTS_APP_EXPIRES_AT'] %>
      encryption_type: <%= ENV['WEBSERVICE_ENCRYPTION_TYPE'] %>
    login_application:
      secret_key: <%= ENV['WEBSERVICE_LOGIN_APP_SECRET'] %>
      expires_at: <%= ENV['WEBSERVICE_LOGIN_APP_EXPIRES_AT'] %>
      encryption_type: <%= ENV['WEBSERVICE_ENCRYPTION_TYPE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
